from __future__ import annotations

from html import escape
from pathlib import Path

import pandas as pd


def write_dashboard(
    output_path: Path,
    title: str,
    summary: pd.DataFrame,
    csv_files: list[Path],
    plot_files: list[Path],
) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    rows = "\n".join(
        "<tr>" + "".join(f"<td>{escape(str(value))}</td>" for value in row) + "</tr>"
        for row in summary.fillna("").astype(str).to_numpy()
    )
    headers = "".join(f"<th>{escape(str(col))}</th>" for col in summary.columns)

    csv_links = "\n".join(
        f'<li><a href="{escape(path.relative_to(output_path.parent).as_posix())}">{escape(path.name)}</a></li>'
        for path in csv_files
    )

    figures = "\n".join(
        f"""
        <figure class="plot" data-name="{escape(path.stem.lower())}">
          <img src="{escape(path.relative_to(output_path.parent).as_posix())}" alt="{escape(path.stem)}">
          <figcaption>{escape(path.stem.replace("_", " "))}</figcaption>
        </figure>
        """
        for path in plot_files
    )

    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <style>
    :root {{
      color-scheme: light;
      --ink: #1d252c;
      --muted: #5b6670;
      --line: #d7dde3;
      --panel: #f7f9fb;
      --accent: #0b6fa4;
    }}
    body {{
      margin: 0;
      font-family: "Segoe UI", Arial, sans-serif;
      color: var(--ink);
      background: white;
    }}
    header {{
      padding: 28px 36px 18px;
      border-bottom: 1px solid var(--line);
      background: var(--panel);
    }}
    h1 {{
      margin: 0 0 8px;
      font-size: 28px;
      font-weight: 650;
      letter-spacing: 0;
    }}
    main {{
      padding: 24px 36px 40px;
      max-width: 1480px;
      margin: 0 auto;
    }}
    .controls {{
      display: flex;
      gap: 14px;
      align-items: end;
      flex-wrap: wrap;
      margin-bottom: 22px;
    }}
    label {{
      display: grid;
      gap: 6px;
      font-size: 13px;
      color: var(--muted);
    }}
    select, input {{
      min-width: 220px;
      padding: 9px 10px;
      border: 1px solid var(--line);
      border-radius: 6px;
      background: white;
      color: var(--ink);
      font-size: 14px;
    }}
    section {{
      margin: 28px 0;
    }}
    table {{
      border-collapse: collapse;
      width: 100%;
      font-size: 13px;
    }}
    th, td {{
      border: 1px solid var(--line);
      padding: 8px 10px;
      text-align: left;
      white-space: nowrap;
    }}
    th {{
      background: var(--panel);
      position: sticky;
      top: 0;
    }}
    .table-wrap {{
      overflow-x: auto;
      border: 1px solid var(--line);
      border-radius: 8px;
    }}
    .gallery {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(420px, 1fr));
      gap: 22px;
    }}
    figure {{
      margin: 0;
      border: 1px solid var(--line);
      border-radius: 8px;
      overflow: hidden;
      background: white;
    }}
    img {{
      width: 100%;
      display: block;
      background: white;
    }}
    figcaption {{
      padding: 10px 12px;
      color: var(--muted);
      border-top: 1px solid var(--line);
      text-transform: capitalize;
    }}
    a {{
      color: var(--accent);
    }}
    @media (max-width: 650px) {{
      header, main {{ padding-left: 16px; padding-right: 16px; }}
      .gallery {{ grid-template-columns: 1fr; }}
      select, input {{ min-width: 100%; }}
    }}
  </style>
</head>
<body>
  <header>
    <h1>{escape(title)}</h1>
    <div>CSV exports and high-resolution PNG plots generated by the IOP probe processing pipeline.</div>
  </header>
  <main>
    <div class="controls">
      <label>
        Plot group
        <select id="group-filter">
          <option value="">All plots</option>
          <option value="overview">Overview</option>
          <option value="heatmap">ACS heatmaps</option>
          <option value="spectra">Spectra</option>
          <option value="alh">aLH / temperature</option>
          <option value="lab">Lab stats</option>
        </select>
      </label>
      <label>
        Search plots
        <input id="plot-search" type="search" placeholder="temperature, down, spectra">
      </label>
    </div>

    <section>
      <h2>Summary</h2>
      <div class="table-wrap">
        <table>
          <thead><tr>{headers}</tr></thead>
          <tbody>{rows}</tbody>
        </table>
      </div>
    </section>

    <section>
      <h2>CSV Files</h2>
      <ul>{csv_links}</ul>
    </section>

    <section>
      <h2>Plots</h2>
      <div class="gallery" id="gallery">{figures}</div>
    </section>
  </main>
  <script>
    const groupFilter = document.getElementById("group-filter");
    const search = document.getElementById("plot-search");
    const plots = Array.from(document.querySelectorAll(".plot"));
    function applyFilters() {{
      const group = groupFilter.value;
      const term = search.value.trim().toLowerCase();
      plots.forEach(plot => {{
        const name = plot.dataset.name;
        const groupOk = !group || name.includes(group);
        const termOk = !term || name.includes(term);
        plot.style.display = groupOk && termOk ? "" : "none";
      }});
    }}
    groupFilter.addEventListener("change", applyFilters);
    search.addEventListener("input", applyFilters);
  </script>
</body>
</html>
"""
    output_path.write_text(html, encoding="utf-8")
    return output_path

